/* eslint-disable */
export const Data = [
  {
    symbol: 'A',
    sector: 'Technology',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Technology',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Technology',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Real Estate',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Real Estate',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Real Estate',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Consumer Cyclical',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Consumer Cyclical',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Consumer Cyclical',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Basic Materials',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Basic Materials',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Basic Materials',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Industrials',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Industrials',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Industrials',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Energy',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Energy',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Energy',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Consumer Defensive',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Consumer Defensive',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Consumer Defensive',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Healthcare',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Healthcare',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Healthcare',
    companyName: 'Cccc',
    price: '3',
  },
  {
    symbol: 'A',
    sector: 'Financial Services',
    companyName: 'Aaaa',
    price: '1',
  },
  {
    symbol: 'B',
    sector: 'Financial Services',
    companyName: 'Bbbb',
    price: '2',
  },
  {
    symbol: 'C',
    sector: 'Financial Services',
    companyName: 'Cccc',
    price: '3',
  },

];
